[project]
name = "bookkeeper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.20.0",
]

[tool.uv]
package = true

[tool.uv.sources]
